apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-application
  namespace: migration
  labels:
    app: post-application
spec:
  selector:
    matchLabels:
      app: post-application
  template:
    metadata:
      labels:
        app: post-application
    spec:
      containers:
        - name: post-application
          image: my-private-registry/postapp:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10