apiVersion: v1
kind: Service
metadata:
  name: user-application
  namespace: migration
  labels:
    app: user-application
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: user-application
